**Training a neural network to calculate a product using tensorflow**

First we import numpy and tensorflow

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

Create training data randomly generated values in [0,1] with uniform distribution

In [ ]:

def create_data(n_observations):
    train_data = np.random.rand(2*n_observations).reshape((n_observations, 2))
    label_data = train_data[:,0] * train_data[:,1]
    return train_data, label_data


In [ ]:
X, y = create_data(10000)

print(X)
print(y)


[[0.20543641 0.35332489]
 [0.13085194 0.55989433]
 [0.48859838 0.70393276]
 ...
 [0.37104348 0.37135658]
 [0.04091198 0.66394738]
 [0.95704796 0.55724924]]
[0.0725858  0.07326326 0.34394041 ... 0.13778944 0.0271634  0.53331425]


**Creating the model**

Input has a shape of 2 (pair of values)

3 layers of neurons

2 dense layers with 16 neurons each and relu activation function

last dense layer for an output of a single numerical value linear activation

In [ ]:
model = keras.Sequential([
        keras.Input(shape=(2,)),
        layers.Dense(16, activation="relu"),
        layers.Dense(16, activation="relu"),
        layers.Dense(1, activation="linear"),
])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            48 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 337 (1.32 KB)

 Trainable params: 337 (1.32 KB)

 Non-trainable params: 0 (0.00 B)

Compiling the model will set up optimizer, loss, etc.
Training is done in batches. We use 10 epochs of training

In [ ]:
model.compile(optimizer='SGD', loss='mean_squared_error')
model.fit(X, y, epochs=10, batch_size=100)




Epoch 1/10
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3772e-04
Epoch 2/10
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2720e-04
Epoch 3/10
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.2377e-04
Epoch 4/10
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1705e-04
Epoch 5/10
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1585e-04
Epoch 6/10
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.1295e-04
Epoch 7/10
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.9553e-04
Epoch 8/10
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.6606e-04
Epoch 9/10
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.8870e-04
Epoch 10/10
100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.7362e-04


We create a small test dataset to test the output of our model. Compare results with test_y target values

In [ ]:
test_data, test_y = create_data(6)
results = model.predict(test_data)

print(test_data)
print(np.transpose(results))
print(test_y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[[0.39094077 0.0142869 ]
 [0.69987808 0.17639573]
 [0.78872653 0.74392296]
 [0.43525753 0.64013521]
 [0.72056724 0.05220836]
 [0.70979824 0.42483017]]
[[0.01755043 0.10832167 0.60591424 0.25684234 0.05902602 0.28274325]]
[0.00558533 0.1234555  0.58675177 0.27862367 0.03761963 0.30154371]
